/* Generated by decomp/tools/objdefgen.py from Fellowship.rfl. Do not edit.
 *
 * The engine's message registry: 54 records of {name, value}, where the value is
 * the message id the engine dispatches on, sparse above 0x100.
 *
 * Verify with: python decomp/tools/objdefgen.py --verify <dir>
 */

#include "registry.h"

static const OF_NamedValue g_messages[] = {
    { "<none>", 0x00000000u },
    { "On", 0x00000001u },
    { "Off", 0x00000002u },
    { "Toggle", 0x00000003u },
    { "Enable", 0x00000004u },
    { "Disable", 0x00000005u },
    { "Triggered", 0x00000006u },
    { "Reverse", 0x00000007u },
    { "Increment", 0x00000008u },
    { "Decrement", 0x00000009u },
    { "Reset", 0x0000000au },
    { "BlowUp", 0x0000000bu },
    { "Destroy", 0x0000000cu },
    { "Prefetch", 0x0000000du },
    { "Lock", 0x0000000eu },
    { "Unlock", 0x0000000fu },
    { "Pause", 0x00000010u },
    { "Test", 0x00000011u },
    { "InvulnerabilityOn", 0x0000005au },
    { "InvulnerabilityOff", 0x0000005bu },
    { "Arm", 0x00000064u },
    { "Disarm", 0x00000065u },
    { "Fire", 0x00000066u },
    { "AmmoEject", 0x00000067u },
    { "Stow", 0x0000006bu },
    { "Equip", 0x0000006cu },
    { "AllowCombo", 0x0000006du },
    { "DisallowCombo", 0x0000006eu },
    { "Attach", 0x0000006fu },
    { "CanAttack", 0x00000070u },
    { "CannotAttack", 0x00000071u },
    { "AttackEffect", 0x00000072u },
    { "CanImpale", 0x00000073u },
    { "CannotImpale", 0x00000074u },
    { "ImpaleThrow", 0x00000075u },
    { "DropItem", 0x00000096u },
    { "SpawnItems", 0x00000097u },
    { "FootStep_Light", 0x000000c8u },
    { "FootStep_Heavy", 0x000000c9u },
    { "FootStep_Scuff", 0x000000cau },
    { "FootStep_Land", 0x000000cbu },
    { "FootStep_NoDetect", 0x000000ccu },
    { "MorphCharacter", 0x000000dcu },
    { "ThrowWeapon", 0x000000e6u },
    { "AttachThrownWeapon", 0x000000e7u },
    { "MoveWeaponDuringThrow", 0x000000e8u },
    { "HealthChange", 0x0000012cu },
    { "StartConversation", 0x0000012du },
    { "EndConversation", 0x0000012eu },
    { "QuestStart", 0x0000015eu },
    { "QuestComplete", 0x0000015fu },
    { "StartInteract", 0x00000190u },
    { "EndInteract", 0x00000191u },
    { "SpawnEffect", 0x000001c2u },
};

const OF_NamedValueInterface g_messageInterface = {
    54u,
    g_messages,
};
