/* Generated by decomp/tools/objdefgen.py from Fellowship.rfl. Do not edit.
 *
 * The engine's ObjType registry: 19 categories, {id, name}. Every ObjectDef's
 * +0x04 field holds one of these ids.
 *
 * Verify with: python decomp/tools/objdefgen.py --verify <dir>
 */

#include "objtype.h"

static const OF_ObjType g_objtypes[] = {
    { 1u, "Material" },
    { 2u, "Don't Use" },
    { 3u, "Player" },
    { 4u, "System" },
    { 5u, "Debug" },
    { 6u, "Flying Enemy" },
    { 7u, "Ground Enemy" },
    { 8u, "Ground Object" },
    { 9u, "Projectile" },
    { 10u, "Item" },
    { 11u, "Powerup" },
    { 12u, "Special Effect" },
    { 13u, "Damage Effect" },
    { 14u, "Light Source" },
    { 15u, "HUD" },
    { 16u, "Attack" },
    { 17u, "Behavior" },
    { 18u, "GUI" },
    { 19u, "Root Behavior" },
};

const OF_ObjTypeInterface g_objTypeInterface = {
    19u,
    g_objtypes,
};
