/* registry.h - the engine's two {name, value} registries.
 *
 * LandType (192 records) and Message (54). Both are published exactly the way
 * the ObjectDef and ObjType registries are: a C++ static initialiser stores a
 * count and a table address into a pair of globals at DLL load, and the matching
 * export returns the address of that pair. Four registries, one mechanism.
 *
 * Field order is the reverse of OF_ObjType's - name first, then the value -
 * which matters only because the two records are otherwise the same eight bytes
 * and reading one as the other would resolve every entry one field off without
 * looking wrong.
 *
 * Both tables are generated by `python decomp/tools/objdefgen.py --emit` and
 * compared against the retail image by `--verify`.
 */

#ifndef OF_REGISTRY_H
#define OF_REGISTRY_H

typedef struct OF_NamedValue {
    const char  *name;  /* +0x00 */
    unsigned int value; /* +0x04  a land type's flags, or a message's id */
} OF_NamedValue;

typedef struct OF_NamedValueInterface {
    unsigned int          count;
    const OF_NamedValue  *table;
} OF_NamedValueInterface;

extern const OF_NamedValueInterface g_landTypeInterface;
extern const OF_NamedValueInterface g_messageInterface;

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(OF_NamedValue) == 8, "OF_NamedValue must be 8 bytes");
#endif

#endif /* OF_REGISTRY_H */
